---
- name: Install i3-gaps
  pacaur: name=i3-gaps-git state=present
  become: yes
  become_user: "{{ username }}"

- name: Install i3blocks
  pacaur: name=i3blocks-gaps-git state=present
  become: yes
  become_user: "{{ username }}"

- name: Install i3lock
  pacman: name=i3lock state=present

- name: Install rofi
  pacman: name=rofi state=present

- name: Create i3 configuration directory for {{ username }}
  file:
    path: /home/{{ username }}/.config/i3
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy i3 config for {{ username }}
  copy:
    src: i3/config
    dest: /home/{{ username }}/.config/i3/config
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    force: yes

- name: Start i3 in xinitrc for {{ username }}
  lineinfile:
    dest: /home/{{ username }}/.xinitrc
    state: present
    line: "exec i3 -c ~/.config/i3/config -V >> ~/.config/i3/log-$(date +'%F-%k-%M-%S') 2>&1"

- name: Create i3blocks configuration directory for {{ username }}
  file:
    path: /home/{{ username }}/.config/i3/blocks
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755

- name: Copy i3blocks config for {{ username }}
  copy:
    src: i3/blocks/i3blocks.conf
    dest: /home/{{ username }}/.config/i3/blocks/i3blocks.conf
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    force: yes
