---
- name: Install xorg
  pacman: name=xorg state=present

- name: Install xinit
  pacman: name=xorg-xinit state=present

- name: Install i3-wm
  pacman: name=i3-wm state=present

- name: Install i3status
  pacman: name=i3status state=present

- name: Install i3lock
  pacman: name=i3lock state=present

- name: Install dmenu
  pacman: name=dmenu state=present

- name: Start xorg on login for {{ username }}
  lineinfile:
    dest: /home/{{ username }}/.zprofile
    state: present
    line: '[ -z "$DISPLAY" -a "$(fgconsole)" -eq 1 ] && exec startx'

- name: Copy default xinitrc to {{ username }}'s home directory
  copy:
    src: /etc/X11/xinit/xinitrc
    remote_src: True
    dest: /home/{{ username }}/.xinitrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    force: no

- name: Remove default window manager configuration from xinitrc for {{ username }}
  lineinfile:
    dest: /home/{{ username }}/.xinitrc
    state: absent
    regexp: '(twm|xclock|xterm)'

- name: Start i3 in xinitrc for {{ username }}
  lineinfile:
    dest: /home/{{ username }}/.xinitrc
    state: present
    line: "exec i3 -V >> ~/.i3log-$(date +'%F-%k-%M-%S') 2>&1"
