---
- name: Install docker
  pacman: name=docker state=present

- name: Start docker service
  service: name=docker enabled=yes state=started

- name: Add user {{ username }} in 'docker' group
  user:
    name: "{{ username }}"
    groups: docker
    append: yes
