---
- include: user.yaml
- include: sudo.yaml
- include: ssh.yaml
- include: pacaur.yaml
- include: fonts.yaml
- include: stats.yaml
- include: wget.yaml
- include: zsh.yaml
- include: terminal.yaml
- include: vim.yaml
- include: go.yaml
- include: docker.yaml
- include: rkt.yaml
- include: chromium.yaml
- include: atom.yaml
