---
- name: Install yajl
  pacman: name=yajl state=present

- name: Install cower
  include: aur/pkg.yaml pkg_name=cower makepkg_nonroot_user={{ username }}

- name: Install pacaur
  include: aur/pkg.yaml pkg_name=pacaur makepkg_nonroot_user={{ username }}
