---
- name: Make sure 'wheel' group exists
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: Add user {{ username }} to 'wheel' group
  user:
    name: "{{ username }}"
    groups: wheel
    append: yes