---
- name: Create user {{ username }}
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    shell: /bin/zsh
    update_password: on_create

- name: Create config directory for {{ username }}
  file:
    path: /home/{{ username }}/.config
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
