---
- name: Make sure 'wheel' group exists
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"

- name: Create user {{ username }} in 'wheel' group
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: wheel
    append: yes
    shell: /bin/zsh
    update_password: on_create

- name: Create config directory for {{ username }}
  file:
    path: /home/{{ username }}/.config
    state: directory
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0755
