---
- name: Install zsh
  pacman: name=zsh state=present

- name: Install oh-my-zsh
  pacaur: name=oh-my-zsh-git state=present
  become: yes
  become_user: "{{ username }}"

- name: Copy default zprofile
  copy:
    src: /etc/zsh/zprofile
    remote_src: True
    dest: /home/{{ username }}/.zprofile
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    force: no

- name: Copy default zshrc
  copy:
    src: /usr/share/oh-my-zsh/zshrc
    remote_src: True
    dest: /home/{{ username }}/.zshrc
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: 0644
    force: no
