---
- name: Install virtualbox-guest-modules-arch
  pacman: name=virtualbox-guest-modules-arch state=present

- name: Install virtualbox-guest-utils
  pacman: name=virtualbox-guest-utils state=present

- name: Start virtualbox service
  service: name=vboxservice enabled=yes state=started
