- name: Start VirtualBox guest services in xinitrc for {{ username }}
  lineinfile:
    dest: /home/{{ username }}/.xinitrc
    state: present
    line: "VBoxClient-all"
    insertbefore: "^exec i3"
